import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {formBindings} from './helpers/form-db.js';
import {acceptForm,processForm,sweepForms} from '../src/forms.js';
import {sweepIntake} from '../src/intake.js';
import {sendContactReceipt,sendApplyReceipt,sendVolunteerReceipt} from '../src/receipts.js';
let original;
beforeEach(()=>{original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('offline test forbids network')}});
afterEach(()=>{globalThis.fetch=original});
const sub={name:'Offline Example',email:'offline@example.com',message:'Original note\nsecond line <not HTML>',tier:'Teammate',amount:500,type:'Giving or sponsoring',source:'Sponsorship page'};
function setup(){const mail=[],env={...formBindings(),SEND_EMAIL:{send:async m=>{mail.push(m);return {messageId:'offline-provider-'+mail.length}}}};return {env,mail}}
test('email can recover the sponsor note and tier without ClickUp or CRM',async()=>{const {env,mail}=setup();const a=await acceptForm(env,'contact',sub);await processForm(env,a.id);await sweepIntake(env);const ack=mail.find(x=>x.to===sub.email);assert.equal(ack.bcc,'hello@adapttolife.org');assert(ack.text.includes(sub.message));assert(ack.text.includes('Teammate ($500)'));assert(ack.text.includes('not a payment or commitment'));assert(ack.text.includes(a.id));assert(ack.html.includes(a.id));assert.equal(ack.headers['X-ATL-Intake-ID'],a.id);assert.equal(ack.headers['Auto-Submitted'],'auto-generated');assert.equal(ack.replyTo,'hello@adapttolife.org');assert(ack.html.includes('&lt;not HTML&gt;'));assert(!ack.html.includes('<not HTML>'));const row=env.WAIVERS_DB.sql.prepare("SELECT * FROM form_deliveries WHERE channel='receipt'").get();const receipt=JSON.parse(row.receipt);assert.equal(receipt.messageId,'offline-provider-1');assert.equal(receipt.status,'accepted');assert.equal(receipt.bcc,'hello@adapttolife.org');assert.equal(row.state,'done')});
test('hung ClickUp cannot delay the correspondence acknowledgment',async()=>{const {env,mail}=setup();env.CLICKUP_TOKEN='offline-only';env.CLICKUP_CONTACTS_LIST_ID='offline-list';let entered,release;const started=new Promise(r=>entered=r);globalThis.fetch=async()=>{entered();return new Promise(r=>release=r)};const a=await acceptForm(env,'contact',sub);const processing=processForm(env,a.id);await started;try{assert.equal(mail.length,1);assert.equal(env.WAIVERS_DB.sql.prepare("SELECT state FROM form_deliveries WHERE channel='receipt'").get().state,'done')}finally{release(new Response('explicit test failure',{status:503}));await processing}});
test('no returned provider ID is review, not fabricated success or a blind resend',async()=>{const {env,mail}=setup();env.SEND_EMAIL.send=async m=>{mail.push(m);return {}};const a=await acceptForm(env,'contact',sub);await processForm(env,a.id);await sweepForms(env);assert.equal(mail.length,1);const row=env.WAIVERS_DB.sql.prepare("SELECT * FROM form_deliveries WHERE channel='receipt'").get();assert.equal(row.state,'review');assert.equal(row.receipt,null)});
test('duplicate dispatch retains one acknowledgment and its actual ID',async()=>{const {env,mail}=setup();const id=crypto.randomUUID();await acceptForm(env,'contact',sub,id);await Promise.all([processForm(env,id),processForm(env,id)]);await sweepForms(env);assert.equal(mail.length,1);assert.equal(JSON.parse(env.WAIVERS_DB.sql.prepare("SELECT receipt FROM form_deliveries WHERE channel='receipt'").get().receipt).messageId,'offline-provider-1')});
test('grant and volunteer receipt audience is not widened by the sponsor change',async()=>{for(const fn of [sendApplyReceipt,sendVolunteerReceipt]){const {env,mail}=setup();const result=await fn({...env,INTAKE_SEPARATE_NOTIFICATION:true,INTAKE_CAPTURE_RECEIPT:true,INTAKE_SUBMISSION_ID:crypto.randomUUID()},{name:'Offline',email:sub.email,roles:['Offline role'],bring:'PRIVATE',about:'PRIVATE',need:'PRIVATE'});assert(result.messageId);assert.equal(mail.length,1);assert.equal(mail[0].bcc,undefined);assert.equal(mail[0].cc,undefined)}});
test('invalid reference is rejected, not normalized or added to headers',async()=>{const {env,mail}=setup();const result=await sendContactReceipt({...env,INTAKE_CAPTURE_RECEIPT:true,INTAKE_SUBMISSION_ID:'\r\nBcc: other@example.com'},sub);assert.equal(result,false);assert.equal(mail.length,0)});
test('ordinary legacy callers retain the boolean receipt API',async()=>{const {env}=setup();assert.equal(await sendContactReceipt(env,sub),true)});
