import {test,beforeEach,afterEach} from 'node:test';
let originalFetch;
beforeEach(()=>{originalFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('Offline test forbids live network')}});
afterEach(()=>{globalThis.fetch=originalFetch});
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {acceptForm,processForm,sweepForms,intakeProjection} from '../src/forms.js';
import worker from '../src/index.js';
import {formBindings} from './helpers/form-db.js';
const sub={name:'Offline Julia',email:'offline@example.com',message:'Offline scenario',type:'Giving or sponsoring',source:'Sponsorship page: Teammate ($500)',tier:'Teammate',amount:500};
function env(){return {...formBindings(),CLICKUP_TOKEN:'offline',CLICKUP_CONTACTS_LIST_ID:'contact',CLICKUP_APPLICATIONS_LIST_ID:'apply',CLICKUP_VOLUNTEERS_LIST_ID:'volunteer',TURNSTILE_MODE:'off'};}
function count(e,table){return e.WAIVERS_DB.sql.prepare(`SELECT count(*) n FROM ${table}`).get().n;}
function states(e){return e.WAIVERS_DB.sql.prepare('SELECT channel,state FROM form_deliveries ORDER BY channel').all().map(r=>[r.channel,r.state]);}
async function withFetch(fn,body){const old=globalThis.fetch;globalThis.fetch=fn;try{return await body()}finally{globalThis.fetch=old}}

test('durable row and all delivery work exist before acknowledgement even without ctx',async()=>{const e=env(),a=await acceptForm(e,'contact',sub);assert(a.ok);assert.equal(count(e,'form_submissions'),1);assert.equal(count(e,'form_deliveries'),3);assert(states(e).every(r=>r[1]==='pending'));});
test('D1 write failure is not success and creates no downstream effects',async()=>{const e=env();e.WAIVERS_DB.batch=async()=>{throw Error('offline fail')};assert.equal((await acceptForm(e,'contact',sub)).status,503);assert.equal(count(e,'form_submissions'),0);});
test('D1 batch transaction rolls back if outbox insertion fails',async()=>{const e=env();e.WAIVERS_DB.sql.exec('DROP TABLE form_deliveries');assert.equal((await acceptForm(e,'contact',sub)).status,503);assert.equal(count(e,'form_submissions'),0);});
test('overlapping identical submissions have one source and one set of work',async()=>{const e=env(),id=crypto.randomUUID();const a=await Promise.all([acceptForm(e,'contact',sub,id),acceptForm(e,'contact',sub,id)]);assert(a.every(r=>r.ok));assert.equal(count(e,'form_submissions'),1);assert.equal(count(e,'form_deliveries'),3);});
test('same ID with changed content cannot overwrite or disclose the original',async()=>{const e=env(),id=crypto.randomUUID();await acceptForm(e,'contact',sub,id);const a=await acceptForm(e,'contact',{...sub,message:'changed'},id);assert.equal(a.status,409);assert.equal(JSON.parse(e.WAIVERS_DB.sql.prepare('SELECT payload FROM form_submissions').get().payload).message,sub.message);});
test('grant/volunteer sensitive story is absent from shared projection',()=>{for(const kind of ['apply','volunteer'])assert(!JSON.stringify(intakeProjection({kind},{...sub,about:'SECRET',need:'SECRET',bring:'SECRET'})).includes('SECRET'));});
test('all independent channels complete once and double dispatch cannot double-send',async()=>{const e=env(),sent=[],posts=[];e.SEND_EMAIL={send:async m=>{sent.push(m);return {messageId:'offline-mail-'+sent.length}}};await withFetch(async(url,opts)=>{assert(String(url).includes('clickup'));posts.push(JSON.parse(opts.body));return Response.json({id:'offline-task',url:'https://app.clickup.com/t/offline-task'})},async()=>{const a=await acceptForm(e,'contact',sub);await Promise.all([processForm(e,a.id),processForm(e,a.id)]);await sweepForms(e);assert(states(e).every(r=>r[1]==='done'));assert.equal(sent.length,1);assert.equal(posts.length,1);assert(posts[0].markdown_description.includes(a.id));assert.equal(sent[0].bcc,'hello@adapttolife.org');assert.equal(e.INTAKE.sql.prepare('SELECT count(*) n FROM intake').get().n,1)});});
test('missing ClickUp does not block intake and receipt; corrected config retries',async()=>{const e=env();delete e.CLICKUP_TOKEN;const sent=[];e.SEND_EMAIL={send:async m=>{sent.push(m);return {messageId:'offline-mail-'+sent.length}}};await withFetch(async()=>Response.json({id:'fixed',url:'https://app.clickup.com/t/fixed'}),async()=>{const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);assert.deepEqual(states(e),[['clickup','pending'],['intake','done'],['receipt','done']]);e.CLICKUP_TOKEN='offline';await sweepForms(e);assert(states(e).every(r=>r[1]==='done'));assert.equal(sent.length,1)});});
test('ClickUp 500 is ambiguous, never automatically POSTed twice',async()=>{const e=env();let posts=0;await withFetch(async()=>{posts++;return new Response('uncertain',{status:500})},async()=>{const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);await sweepForms(e);assert.equal(posts,1);assert(states(e).some(r=>r[0]==='clickup'&&r[1]==='review'));assert(states(e).some(r=>r[0]==='intake'&&r[1]==='done'))});});
test('ClickUp 429 is a definite failure and can recover',async()=>{const e=env();let posts=0;await withFetch(async()=>++posts===1?new Response('rate limited',{status:429}):Response.json({id:'fixed'}),async()=>{const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);assert(states(e).some(r=>r[0]==='clickup'&&r[1]==='pending'));await sweepForms(e);assert.equal(posts,2)});});
test('mail uncertainty remains visible and is never automatically resent',async()=>{const e=env();let sent=0;delete e.CLICKUP_TOKEN;e.SEND_EMAIL={send:async()=>{sent++;throw Error('unknown delivery')}};const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);await sweepForms(e);assert.equal(sent,1);assert(states(e).some(r=>r[0]==='receipt'&&r[1]==='review'));});
test('crash after cross-DB mirror before stamp cannot duplicate CRM source',async()=>{const e=env();const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);e.WAIVERS_DB.sql.prepare("UPDATE form_deliveries SET state='running',started_at='2000-01-01' WHERE channel='intake'").run();await sweepForms(e);assert.equal(e.INTAKE.sql.prepare('SELECT count(*) n FROM intake').get().n,1);});
test('crash during non-idempotent write is review, never blindly re-issued',async()=>{const e=env();await acceptForm(e,'contact',sub);e.WAIVERS_DB.sql.prepare("UPDATE form_deliveries SET state='running',started_at='2000-01-01' WHERE channel IN ('receipt','clickup')").run();await sweepForms(e);assert.deepEqual(states(e),[['clickup','review'],['intake','done'],['receipt','review']]);});
test('public sponsor request is validated and durable with tier/note, never marketing',async()=>{const e=env();const res=await worker.fetch(new Request('https://adapttolife.org/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fn:'Offline',em:'offline@example.com',rsn:'Giving or sponsoring',msg:'Keep this note',source:'Sponsorship page: Teammate ($500)',sponsor_tier:'Teammate',sponsor_amount:'500'})}),e);assert.equal(res.status,200);const row=e.WAIVERS_DB.sql.prepare('SELECT * FROM form_submissions').get();const data=JSON.parse(row.payload);assert.equal(data.message,'Keep this note');assert.equal(data.tier,'Teammate');assert.equal(data.amount,500);assert.equal(count(e,'form_deliveries'),3);});
test('real challenge remains mandatory when not explicitly disabled in isolated test',async()=>{const e=env();delete e.TURNSTILE_MODE;const res=await worker.fetch(new Request('https://adapttolife.org/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fn:'Offline',em:'offline@example.com',msg:'test'})}),e);assert.notEqual(res.status,200);assert.equal(count(e,'form_submissions'),0);});
test('browser retry key survives refreshed token, changes on edits and resets on success',()=>{const form={addEventListener:(name,fn)=>form[name]=fn};const c={window:{},crypto};vm.runInNewContext(readFileSync(new URL('../public/js/form-submission.js',import.meta.url),'utf8'),c);const make=c.window.ATLFormSubmission;const a=make(form,{em:'offline@example.com',cf_token:'first'}).submission_id;assert.equal(make(form,{em:'offline@example.com',cf_token:'second'}).submission_id,a);assert.notEqual(make(form,{em:'other@example.com'}).submission_id,a);form.reset();assert.notEqual(make(form,{em:'offline@example.com'}).submission_id,a);});
