import {test,beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {setImmediate as tick} from 'node:timers/promises';
import {formBindings} from './helpers/form-db.js';
import {acceptForm,processForm,sweepForms} from '../src/forms.js';
import {sweepIntake} from '../src/intake.js';
const sub={name:'Offline',email:'offline@example.com',phone:'offline phone',type:'Giving or sponsoring',tier:'Coach',amount:2500,source:'Sponsorship page',message:'Original\n<note> & exact words'};
let old;
beforeEach(()=>{old=fetch;globalThis.fetch=async()=>{throw Error('offline only')}});afterEach(()=>{globalThis.fetch=old});
function setup(){const mail=[];const e={...formBindings(),SEND_EMAIL:{send:async m=>{mail.push(m);return {messageId:m.to===sub.email?'visitor-id':'house-id'}}}};return {e,mail};}
const rec=e=>e.WAIVERS_DB.sql.prepare('SELECT * FROM form_record_deliveries').get();
async function until(fn){for(let i=0;i<100;i++){if(fn())return;await tick();}assert.fail('independent step did not complete');}
test('original work commits with accepted source; missing original outbox rolls back the whole submission',async()=>{const {e}=setup();e.WAIVERS_DB.sql.exec('DROP TABLE form_record_deliveries');assert.equal((await acceptForm(e,'contact',sub)).status,503);assert.equal(e.WAIVERS_DB.sql.prepare('SELECT COUNT(*) n FROM form_submissions').get().n,0);});
test('rejected customer acknowledgment cannot lose the full house original or duplicate it through the shared sweeper',async()=>{const {e,mail}=setup();e.SEND_EMAIL.send=async m=>{mail.push(m);if(m.to===sub.email)throw Error('recipient suppressed');return {messageId:'house-real-fixture-id'}};const a=await acceptForm(e,'contact',{...sub,cf_token:'DO-NOT-FORWARD',about:'DO-NOT-FORWARD'});await Promise.all([processForm(e,a.id),processForm(e,a.id)]);await sweepForms(e);await sweepIntake(e);const house=mail.filter(m=>m.to==='hello@adapttolife.org');assert.equal(house.length,1);const m=house[0];assert.equal(m.cc,undefined);assert.equal(m.bcc,undefined);assert.equal(m.replyTo,sub.email);assert.equal(m.headers['X-ATL-Record'],'original-request');assert.equal(m.headers['X-ATL-Intake-ID'],a.id);assert.equal(m.headers['Auto-Submitted'],'auto-generated');for(const value of [sub.message,sub.tier,'2500',sub.email,sub.source,a.id])assert(m.text.includes(value));assert(!m.text.includes('DO-NOT-FORWARD'));assert(!m.html.includes('<note>'));assert.equal(rec(e).state,'done');assert.equal(JSON.parse(rec(e).receipt).messageId,'house-real-fixture-id');assert(rec(e).mirrored_at);assert(e.INTAKE.sql.prepare('SELECT notified_at FROM intake').get().notified_at);assert.equal(e.INTAKE.sql.prepare('SELECT COUNT(*) n FROM intake_delivery_claims').get().n,0);assert.equal(e.WAIVERS_DB.sql.prepare("SELECT state FROM form_deliveries WHERE channel='receipt'").get().state,'review');});
test('house rejection does not block acknowledgment and stays review without replay',async()=>{const {e,mail}=setup();e.SEND_EMAIL.send=async m=>{mail.push(m);if(m.to!==sub.email)throw Error('house rejected');return {messageId:'visitor-id'}};const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);await sweepForms(e);await sweepIntake(e);assert.equal(mail.length,2);assert.equal(rec(e).state,'review');assert.equal(e.WAIVERS_DB.sql.prepare("SELECT state FROM form_deliveries WHERE channel='receipt'").get().state,'done');assert.equal(e.INTAKE.sql.prepare('SELECT notified_at FROM intake').get().notified_at,null);});
for(const hung of ['visitor','house'])test(`hung ${hung} transport does not hold the other correspondence path or CRM`,async()=>{const {e,mail}=setup();e.CLICKUP_TOKEN='offline';e.CLICKUP_CONTACTS_LIST_ID='offline';let release;const deferred=new Promise(r=>release=r);globalThis.fetch=async()=>Response.json({id:'offline-task'});e.SEND_EMAIL.send=async m=>{mail.push(m);if((m.to===sub.email)===(hung==='visitor'))return deferred;return {messageId:'independent-id'}};const a=await acceptForm(e,'contact',sub),p=processForm(e,a.id);try{await until(()=>e.WAIVERS_DB.sql.prepare("SELECT state FROM form_deliveries WHERE channel='clickup'").get().state==='done');await until(()=>hung==='visitor'?rec(e).state==='done':e.WAIVERS_DB.sql.prepare("SELECT state FROM form_deliveries WHERE channel='receipt'").get().state==='done');}finally{release({messageId:'released-id'});await p;}assert.equal(mail.length,2);});
test('missing house provider ID and expired running sends require review, never fabricated acceptance',async()=>{for(const crash of [false,true]){const {e,mail}=setup();e.SEND_EMAIL.send=async m=>{mail.push(m);return m.to===sub.email?{messageId:'visitor'}:{}};const a=await acceptForm(e,'contact',sub);if(crash)e.WAIVERS_DB.sql.prepare("UPDATE form_record_deliveries SET state='running',started_at='2000-01-01'").run();await sweepForms(e);await sweepForms(e);assert.equal(rec(e).state,'review');assert.equal(rec(e).receipt,null);assert.equal(mail.filter(m=>m.to!==sub.email).length,crash?0:1);}});
test('missing binding is retryable, but corrected configuration emits each original once',async()=>{const {e,mail}=setup();const binding=e.SEND_EMAIL;delete e.SEND_EMAIL;const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);assert.equal(rec(e).state,'pending');e.SEND_EMAIL=binding;await sweepForms(e);await sweepForms(e);assert.equal(rec(e).state,'done');assert.equal(mail.filter(m=>m.to!==sub.email).length,1);});
test('cross-database stamp failure retries projection, not either email',async()=>{const {e,mail}=setup();const prepare=e.INTAKE.prepare.bind(e.INTAKE);e.INTAKE.prepare=sql=>{if(sql.startsWith('UPDATE intake SET notified_at=COALESCE'))throw Error('projection down');return prepare(sql)};const a=await acceptForm(e,'contact',sub);await processForm(e,a.id);assert.equal(rec(e).state,'done');assert.equal(rec(e).mirrored_at,null);e.INTAKE.prepare=prepare;await sweepForms(e);assert(rec(e).mirrored_at);assert.equal(mail.length,2);});
test('applications, volunteers and historical contact records are not enrolled by recovery',async()=>{const {e,mail}=setup();for(const kind of ['apply','volunteer'])await acceptForm(e,kind,{...sub,roles:[],about:'PRIVATE',need:'PRIVATE'});const a=await acceptForm(e,'contact',sub);e.WAIVERS_DB.sql.prepare('DELETE FROM form_record_deliveries WHERE submission_id=?').run(a.id);e.WAIVERS_DB.sql.prepare("UPDATE form_deliveries SET state='done'").run();await sweepForms(e);assert.equal(e.WAIVERS_DB.sql.prepare('SELECT COUNT(*) n FROM form_record_deliveries').get().n,0);assert.equal(mail.length,0);});
