import {test} from 'node:test';
import assert from 'node:assert/strict';
import {formBindings} from './helpers/form-db.js';
import {recordIntake,notifyIntakeRow,sweepIntake,runIntakeCanary} from '../src/intake.js';
const entry={site:'adapttolife.org',kind:'sponsor',name:'Offline',email:'offline@example.com',summary:'Offline sponsor',payload:{tier:'Teammate'}};
async function setup(){const e=formBindings(),sent=[];e.SEND_EMAIL={send:async m=>sent.push(m)};const r=await recordIntake(e,entry);assert.equal(r.ok,true);return {e,sent,row:e.INTAKE.sql.prepare('SELECT * FROM intake WHERE id=?').get(r.id)}}
test('record and notification claim are atomic',async()=>{const {e,row}=await setup();assert.equal(e.INTAKE.sql.prepare('SELECT state FROM intake_delivery_claims WHERE intake_id=?').get(row.id).state,'pending')});
test('overlapping sender and sweeper produce one house notification',async()=>{const {e,row,sent}=await setup();await Promise.all([notifyIntakeRow(e,row),sweepIntake(e),notifyIntakeRow(e,row)]);await sweepIntake(e);assert.equal(sent.length,1);assert.equal(sent[0].to,'hello@adapttolife.org');assert.equal(sent[0].replyTo,entry.email)});
test('ambiguous send is visible, not blindly resent',async()=>{const {e,row}=await setup();let n=0;e.SEND_EMAIL={send:async()=>{n++;throw Error('response lost')}};await notifyIntakeRow(e,row);await sweepIntake(e);assert.equal(n,1);assert.equal(e.INTAKE.sql.prepare('SELECT state FROM intake_delivery_claims').get().state,'review')});
test('accepted mail plus failed stamp is not sent again',async()=>{const {e,row,sent}=await setup();const batch=e.INTAKE.batch;e.INTAKE.batch=async()=>{e.INTAKE.batch=batch;throw Error('stamp failed')};await notifyIntakeRow(e,row);await sweepIntake(e);assert.equal(sent.length,1);assert.equal(e.INTAKE.sql.prepare('SELECT state FROM intake_delivery_claims').get().state,'review')});
test('missing mail binding leaves confirmed unsent work retryable',async()=>{const {e,row,sent}=await setup();const sender=e.SEND_EMAIL;delete e.SEND_EMAIL;assert.equal(await notifyIntakeRow(e,row),false);assert.equal(e.INTAKE.sql.prepare('SELECT state FROM intake_delivery_claims').get().state,'pending');e.SEND_EMAIL=sender;await sweepIntake(e);assert.equal(sent.length,1)});
test('an interrupted sender is marked review after lease age',async()=>{const {e,sent}=await setup();e.INTAKE.sql.prepare("UPDATE intake_delivery_claims SET state='sending',started_at='2000-01-01'").run();await sweepIntake(e);assert.equal(sent.length,0);assert.equal(e.INTAKE.sql.prepare('SELECT state FROM intake_delivery_claims').get().state,'review')});
test('legacy row without trusted claim is not automatically replayed',async()=>{const {e,row,sent}=await setup();e.INTAKE.sql.prepare('DELETE FROM intake_delivery_claims').run();assert.equal(await notifyIntakeRow(e,row),false);await sweepIntake(e);assert.equal(sent.length,0)});
test('covered receipts and retired canaries do not send again',async()=>{const e=formBindings();let n=0;e.SEND_EMAIL={send:async()=>n++};await recordIntake(e,{...entry,alreadyNotified:true});await recordIntake(e,{...entry,isCanary:true});await sweepIntake(e);assert.equal(n,0);assert.equal((await runIntakeCanary(new Proxy({},{get(){throw Error('no side effects')}}))).stage,'disabled-by-owner')});
