#!/usr/bin/env node
// Precompute the US state outlines into ONE projected SVG path, at build time.
//
// The alternative was shipping us-atlas (114KB of TopoJSON) plus topojson-client
// to the browser and doing this work on every page load. Neither the topology
// nor the projection ever changes, so doing it once here costs the bundle a
// path string instead of a library plus a dataset.
//
// Run: node scripts/build-basemap.mjs   (writes admin-app/src/lib/basemap.ts)
import { writeFileSync } from "fs";
import { feature, mesh } from "topojson-client";
import { presimplify, simplify, quantile } from "topojson-simplify";
import { geoAlbersUsa, geoPath } from "d3-geo";

const W = 960, H = 500;
const src = "https://cdn.jsdelivr.net/npm/us-atlas@3/states-10m.json";

const raw = await (await fetch(src)).json();

// Simplify BEFORE projecting. The first cut skipped this and emitted 130KB of
// path — worse than the 114KB TopoJSON it was meant to replace, because a
// 1:10m coastline has a vertex every few hundred metres and geoPath faithfully
// writes every one of them. At the size this renders, none of that detail is
// visible: the whole map is 960 units wide, so a vertex 200m apart is well
// under a thousandth of a pixel.
const pre = presimplify(raw);
const topo = simplify(pre, quantile(pre, 0.18));
const states = feature(topo, topo.objects.states);
const projection = geoAlbersUsa().fitSize([W, H], states);
const path = geoPath(projection);

// Interior borders as a mesh (shared edges drawn once, not twice) and the
// nation outline separately, so the two can carry different weights.
const interior = path(mesh(topo, topo.objects.states, (a, b) => a !== b));
const outline = path(feature(topo, topo.objects.nation));

// Round coordinates: sub-pixel precision in a 960-unit viewBox is invisible
// and roughly halves the string.
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(1));

const out = `// GENERATED by scripts/build-basemap.mjs — do not edit.
// US states, projected with geoAlbersUsa fitted to ${W}x${H}. Regenerate if the
// viewBox changes; the runtime uses the SAME projection to place points, so the
// two must agree or every dot lands in the wrong state.
export const BASEMAP_W = ${W};
export const BASEMAP_H = ${H};
export const BASEMAP_OUTLINE = ${JSON.stringify(round(outline))};
export const BASEMAP_INTERIOR = ${JSON.stringify(round(interior))};
`;
writeFileSync("admin-app/src/lib/basemap.ts", out);
console.log(`  basemap: ${(out.length / 1024).toFixed(1)}KB of path data`
  + ` (vs 114KB TopoJSON + a library at runtime)`);
